baseURL = 'https://mpklu.github.io/'
languageCode = 'en-us'
title = 'AI Coding Blog'
theme = 'ananke'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[related]
  includeNewer = true
  threshold = 80
  toLower = true
  [[related.indices]]
    name = 'tags'
    weight = 100
  [[related.indices]]
    name = 'categories'
    weight = 80
  [[related.indices]]
    name = 'date'
    weight = 10

[[menus.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 10

[[menus.main]]
  name = 'News Digests'
  url = '/newsdigests/'
  weight = 20

[[menus.main]]
  name = 'Market News'
  url = '/marketnews/'
  weight = 25

[[menus.main]]
  name = 'RSS'
  url = '/newsdigests/index.xml'
  weight = 30

[params]
  show_reading_time = true
  mainSections = ['posts']
  site_logo = '/images/avatar.png'
  custom_css = ['custom.css']
  author = 'Kun Lu'
  giscusEnable = true
  ttsEnable = true
